version: '3'
  
services:
   wordpress-db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       MYSQL_PORT: 3306

   wordpress:
     depends_on:
       - wordpress-db
     build:
       context: ./docker/
       args:
         BRANCH: "master"
     ports:
       - "7001:443"
     environment:
       WORDPRESS_DB_HOST: wordpress-db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

