name: Unit Tests
on: [push, pull_request_target]

jobs:
  rake:
    name: Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    # always run on push events
    # only run on pull_request_target event when pull request pulls from fork repository
    if: >
      github.event_name == 'push' || 
      github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository 
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.2, 7.3, 7.4]

    steps:
      - uses: actions/checkout@v2

      - uses:  shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - run: composer install

      - run: bash bin/install-wp-tests.sh wordpress_test root '' localhost latest

      - run: composer test

      - run: WP_MULTISITE=1 composer test

      - run: composer lint
